version: "3"
services:
  couchbase-db:
    image: couchbase/server:enterprise-7.1.0
    container_name: couchbase_db_1
    ports:
      - '8091-8094:8091-8094'
      - '11210:11210'
    networks:
      - couchbase-network
    volumes:
      - couchbasedata:/opt/couchbase/var

networks:
  couchbase-network:
    driver: bridge

volumes:
  couchbasedata:
    driver: local
